# Generated by Django 4.1.7 on 2024-01-14 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rank_remove_recourse_group_remove_recourse_science_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
