# Generated by Django 4.1.7 on 2023-04-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_customuser_options_alter_customuser_birth_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.ImageField(default=0, upload_to='Video/'),
            preserve_default=False,
        ),
    ]
