# Generated by Django 4.1.7 on 2023-04-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_video_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birth_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='User/'),
        ),
        migrations.AddField(
            model_name='student',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
