# Generated by Django 4.1.7 on 2023-05-28 18:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_remove_test_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivequestion',
            name='choosen',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
